<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c19a1486-f663-46e0-979e-271096ef8888</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MTSM.Cirrus.Core\MTSM.Cirrus.Core.csproj" />
  </ItemGroup>
</Project>
