// <auto-generated />
using System;
using System.Text.Json;
using MTSM.Cirrus.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MTSM.Cirrus.Migration.Data.Migrations
{
    [DbContext(typeof(CirrusDbContext))]
    [Migration("20260725225040_AddArchiveDeletionLifecycle")]
    partial class AddArchiveDeletionLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cirrus")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveBusinessReference", b =>
                {
                    b.Property<long>("ArchiveObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("archive_object_id");

                    b.Property<int>("BusinessReferenceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("business_reference_type_id");

                    b.Property<string>("ReferenceValue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reference_value");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_type");

                    b.Property<string>("Tenant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ArchiveObjectId", "BusinessReferenceTypeId", "ReferenceValue", "BusinessType", "Tenant")
                        .HasName("pk_archive_business_ref");

                    b.HasIndex("BusinessType", "Tenant")
                        .HasDatabaseName("ix_archive_business_ref_business_type_tenant");

                    b.HasIndex("Tenant", "BusinessType", "ReferenceValue")
                        .HasDatabaseName("ix_archive_business_ref_tenant_business_type_reference_value");

                    b.HasIndex("BusinessReferenceTypeId", "ReferenceValue", "BusinessType", "Tenant")
                        .HasDatabaseName("ix_archive_business_ref_business_reference_type_id_reference_v");

                    b.ToTable("archive_business_ref", "cirrus");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveErrorQueueItem", b =>
                {
                    b.Property<long>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("error_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ErrorId"));

                    b.Property<long?>("ArchiveObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("archive_object_id");

                    b.Property<DateTimeOffset>("ErrorTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("error_timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_type");

                    b.Property<string>("LastErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<bool>("Resolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("resolved");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.HasKey("ErrorId")
                        .HasName("pk_archive_error_queue");

                    b.HasIndex("ArchiveObjectId")
                        .HasDatabaseName("ix_archive_error_queue_archive_object_id");

                    b.HasIndex("Resolved", "NextRetryAt")
                        .HasDatabaseName("ix_archive_error_queue_resolved_next_retry_at");

                    b.ToTable("archive_error_queue", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_archive_error_queue_retry_count", "retry_count >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveEvent", b =>
                {
                    b.Property<long>("ArchiveEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("archive_event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ArchiveEventId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor");

                    b.Property<long>("ArchiveObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("archive_object_id");

                    b.Property<JsonDocument>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.HasKey("ArchiveEventId")
                        .HasName("pk_archive_event");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_archive_event_event_type");

                    b.HasIndex("ArchiveObjectId", "EventTimestamp")
                        .HasDatabaseName("ix_archive_event_archive_object_id_event_timestamp");

                    b.ToTable("archive_event", "cirrus");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveObject", b =>
                {
                    b.Property<long>("ArchiveObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("archive_object_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ArchiveObjectId"));

                    b.Property<string>("ArchiveStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("archive_status");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bucket_name");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("DeletionRequestedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deletion_requested_by");

                    b.Property<string>("EncryptionKeyId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("encryption_key_id");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsWormProtected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_worm_protected");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("original_filename");

                    b.Property<string>("Partner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("partner");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int?>("RetentionPolicyId")
                        .HasColumnType("integer")
                        .HasColumnName("retention_policy_id");

                    b.Property<DateOnly>("RetentionUntil")
                        .HasColumnType("date")
                        .HasColumnName("retention_until");

                    b.Property<string>("Sha256Hash")
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_system");

                    b.Property<string>("StorageVersionId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_version_id");

                    b.HasKey("ArchiveObjectId")
                        .HasName("pk_archive_object");

                    b.HasIndex("ArchiveStatus")
                        .HasDatabaseName("ix_archive_object_archive_status");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("ix_archive_object_archived_at");

                    b.HasIndex("DeletionRequestedAt")
                        .HasDatabaseName("ix_archive_object_deletion_requested_at");

                    b.HasIndex("PurgedAt")
                        .HasDatabaseName("ix_archive_object_purged_at");

                    b.HasIndex("RetentionPolicyId")
                        .HasDatabaseName("ix_archive_object_retention_policy_id");

                    b.HasIndex("RetentionUntil")
                        .HasDatabaseName("ix_archive_object_retention_until");

                    b.HasIndex("Sha256Hash")
                        .HasDatabaseName("ix_archive_object_sha256hash");

                    b.HasIndex("ArchiveStatus", "DeletionRequestedAt")
                        .HasDatabaseName("ix_archive_object_archive_status_deletion_requested_at");

                    b.HasIndex("BucketName", "ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_archive_object_bucket_name_object_key");

                    b.HasIndex("SourceSystem", "FileType", "Partner")
                        .HasDatabaseName("ix_archive_object_source_system_file_type_partner");

                    b.ToTable("archive_object", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_archive_object_deletion_requested", "archive_status <> 'DeletionRequested'\r\nOR (\r\n    deletion_requested_at IS NOT NULL\r\n    AND deletion_requested_by IS NOT NULL\r\n)");

                            t.HasCheckConstraint("ck_archive_object_purged", "archive_status <> 'Purged'\r\nOR purged_at IS NOT NULL");

                            t.HasCheckConstraint("ck_archive_object_size_bytes", "size_bytes >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.BusinessReferenceType", b =>
                {
                    b.Property<int>("BusinessReferenceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("business_reference_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BusinessReferenceTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ReferenceTypeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_type_key");

                    b.HasKey("BusinessReferenceTypeId")
                        .HasName("pk_business_ref_type");

                    b.HasIndex("ReferenceTypeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_business_ref_type_reference_type_key");

                    b.ToTable("business_ref_type", "cirrus");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.RetentionPolicy", b =>
                {
                    b.Property<int>("RetentionPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("retention_policy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RetentionPolicyId"));

                    b.Property<bool>("DeleteAfterExpiry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("delete_after_expiry");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("policy_name");

                    b.Property<int>("RetentionYears")
                        .HasColumnType("integer")
                        .HasColumnName("retention_years");

                    b.Property<bool>("WormRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("worm_required");

                    b.HasKey("RetentionPolicyId")
                        .HasName("pk_retention_policy");

                    b.HasIndex("PolicyName")
                        .IsUnique()
                        .HasDatabaseName("ix_retention_policy_policy_name");

                    b.ToTable("retention_policy", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_retention_policy_retention_years", "retention_years >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveBusinessReference", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.ArchiveObject", "ArchiveObject")
                        .WithMany("BusinessReferences")
                        .HasForeignKey("ArchiveObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_archive_business_ref_archive_objects_archive_object_id");

                    b.HasOne("MTSM.Cirrus.Core.Entities.BusinessReferenceType", "BusinessReferenceType")
                        .WithMany("BusinessReferences")
                        .HasForeignKey("BusinessReferenceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_archive_business_ref_business_reference_types_business_refe");

                    b.Navigation("ArchiveObject");

                    b.Navigation("BusinessReferenceType");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveErrorQueueItem", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.ArchiveObject", "ArchiveObject")
                        .WithMany("Errors")
                        .HasForeignKey("ArchiveObjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_archive_error_queue_archive_objects_archive_object_id");

                    b.Navigation("ArchiveObject");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveEvent", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.ArchiveObject", "ArchiveObject")
                        .WithMany("Events")
                        .HasForeignKey("ArchiveObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_archive_event_archive_objects_archive_object_id");

                    b.Navigation("ArchiveObject");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveObject", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.RetentionPolicy", "RetentionPolicy")
                        .WithMany("ArchiveObjects")
                        .HasForeignKey("RetentionPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_archive_object_retention_policies_retention_policy_id");

                    b.Navigation("RetentionPolicy");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveObject", b =>
                {
                    b.Navigation("BusinessReferences");

                    b.Navigation("Errors");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.BusinessReferenceType", b =>
                {
                    b.Navigation("BusinessReferences");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.RetentionPolicy", b =>
                {
                    b.Navigation("ArchiveObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
