// <auto-generated />
using System;
using System.Text.Json;
using MTSM.Cirrus.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MTSM.Cirrus.Migration.Data.Migrations
{
    [DbContext(typeof(CirrusDbContext))]
    [Migration("20260830152348_AddContentAddressedStorage")]
    partial class AddContentAddressedStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cirrus")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ApiKeyCredential", b =>
                {
                    b.Property<long>("ApiKeyCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("api_key_credential_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ApiKeyCredentialId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash_algorithm");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key_id");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<long>("MachineIdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("machine_identity_id");

                    b.Property<long?>("ReplacedById")
                        .HasColumnType("bigint")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("ApiKeyCredentialId")
                        .HasName("pk_api_key_credential");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("ix_api_key_credential_key_id");

                    b.HasIndex("ReplacedById")
                        .HasDatabaseName("ix_api_key_credential_replaced_by_id");

                    b.HasIndex("MachineIdentityId", "Status")
                        .HasDatabaseName("ix_api_key_credential_machine_identity_id_status");

                    b.ToTable("api_key_credential", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_api_key_credential_expiry", "expires_at IS NULL OR expires_at > created_at");

                            t.HasCheckConstraint("ck_api_key_credential_hash", "hash_algorithm = 'SHA-256' AND octet_length(secret_hash) = 32");

                            t.HasCheckConstraint("ck_api_key_credential_revoked", "status <> 'Revoked' OR revoked_at IS NOT NULL");

                            t.HasCheckConstraint("ck_api_key_credential_status", "status IN ('Active', 'Revoked')");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveBusinessReference", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("ArchiveObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("archive_object_id");

                    b.Property<int>("BusinessReferenceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("business_reference_type_id");

                    b.Property<string>("ReferenceValue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reference_value");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TenantId", "ArchiveObjectId", "BusinessReferenceTypeId", "ReferenceValue", "BusinessType")
                        .HasName("pk_archive_business_ref");

                    b.HasIndex("BusinessReferenceTypeId")
                        .HasDatabaseName("ix_archive_business_ref_business_reference_type_id");

                    b.HasIndex("TenantId", "BusinessType", "ReferenceValue")
                        .HasDatabaseName("ix_archive_business_ref_tenant_id_business_type_reference_value");

                    b.HasIndex("TenantId", "BusinessReferenceTypeId", "ReferenceValue", "BusinessType")
                        .HasDatabaseName("ix_archive_business_ref_tenant_id_business_reference_type_id_r");

                    b.ToTable("archive_business_ref", "cirrus");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveErrorQueueItem", b =>
                {
                    b.Property<long>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("error_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ErrorId"));

                    b.Property<long?>("ArchiveObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("archive_object_id");

                    b.Property<DateTimeOffset>("ErrorTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("error_timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_type");

                    b.Property<string>("LastErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<bool>("Resolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("resolved");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.HasKey("ErrorId")
                        .HasName("pk_archive_error_queue");

                    b.HasIndex("ArchiveObjectId")
                        .HasDatabaseName("ix_archive_error_queue_archive_object_id");

                    b.HasIndex("Resolved", "NextRetryAt")
                        .HasDatabaseName("ix_archive_error_queue_resolved_next_retry_at");

                    b.ToTable("archive_error_queue", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_archive_error_queue_retry_count", "retry_count >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveEvent", b =>
                {
                    b.Property<long>("ArchiveEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("archive_event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ArchiveEventId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor");

                    b.Property<long>("ArchiveObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("archive_object_id");

                    b.Property<JsonDocument>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("ArchiveEventId")
                        .HasName("pk_archive_event");

                    b.HasIndex("TenantId", "EventTimestamp")
                        .HasDatabaseName("ix_archive_event_tenant_id_event_timestamp");

                    b.HasIndex("TenantId", "ArchiveObjectId", "EventTimestamp")
                        .HasDatabaseName("ix_archive_event_tenant_id_archive_object_id_event_timestamp");

                    b.HasIndex("TenantId", "EventType", "EventTimestamp")
                        .HasDatabaseName("ix_archive_event_tenant_id_event_type_event_timestamp");

                    b.ToTable("archive_event", "cirrus");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveObject", b =>
                {
                    b.Property<long>("ArchiveObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("archive_object_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ArchiveObjectId"));

                    b.Property<string>("ArchiveStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("archive_status");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bucket_name");

                    b.Property<long?>("ContentManifestId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_manifest_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("DeletionRequestedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deletion_requested_by");

                    b.Property<string>("EncryptionKeyId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("encryption_key_id");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_type");

                    b.Property<string>("IntegrityCheckLeaseOwner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("integrity_check_lease_owner");

                    b.Property<DateTimeOffset?>("IntegrityCheckLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("integrity_check_lease_until");

                    b.Property<bool>("IsWormProtected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_worm_protected");

                    b.Property<DateTimeOffset?>("LastIntegrityCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_integrity_check_at");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<DateTimeOffset?>("NextIntegrityCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_integrity_check_at");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("original_filename");

                    b.Property<string>("Partner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("partner");

                    b.Property<string>("PurgeLeaseOwner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("purge_lease_owner");

                    b.Property<DateTimeOffset?>("PurgeLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_lease_until");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int?>("RetentionPolicyId")
                        .HasColumnType("integer")
                        .HasColumnName("retention_policy_id");

                    b.Property<DateOnly>("RetentionUntil")
                        .HasColumnType("date")
                        .HasColumnName("retention_until");

                    b.Property<string>("Sha256Hash")
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_system");

                    b.Property<string>("StagingObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("staging_object_key");

                    b.Property<int>("StorageProcessingAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("storage_processing_attempt_count");

                    b.Property<DateTimeOffset?>("StorageProcessingCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("storage_processing_completed_at");

                    b.Property<string>("StorageProcessingErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("storage_processing_error_code");

                    b.Property<string>("StorageProcessingErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("storage_processing_error_message");

                    b.Property<string>("StorageProcessingLeaseOwner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_processing_lease_owner");

                    b.Property<DateTimeOffset?>("StorageProcessingLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("storage_processing_lease_until");

                    b.Property<DateTimeOffset?>("StorageProcessingNextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("storage_processing_next_attempt_at");

                    b.Property<DateTimeOffset?>("StorageProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("storage_processing_started_at");

                    b.Property<string>("StorageProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Completed")
                        .HasColumnName("storage_processing_status");

                    b.Property<DateTimeOffset?>("StorageProcessingVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("storage_processing_verified_at");

                    b.Property<string>("StorageVersionId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_version_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("ArchiveObjectId")
                        .HasName("pk_archive_object");

                    b.HasAlternateKey("TenantId", "ArchiveObjectId")
                        .HasName("ak_archive_objects_tenant_id_archive_object_id");

                    b.HasIndex("ArchiveStatus")
                        .HasDatabaseName("ix_archive_object_archive_status");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("ix_archive_object_archived_at");

                    b.HasIndex("ContentManifestId")
                        .HasDatabaseName("ix_archive_object_content_manifest_id");

                    b.HasIndex("DeletionRequestedAt")
                        .HasDatabaseName("ix_archive_object_deletion_requested_at");

                    b.HasIndex("PurgedAt")
                        .HasDatabaseName("ix_archive_object_purged_at");

                    b.HasIndex("RetentionPolicyId")
                        .HasDatabaseName("ix_archive_object_retention_policy_id");

                    b.HasIndex("RetentionUntil")
                        .HasDatabaseName("ix_archive_object_retention_until");

                    b.HasIndex("Sha256Hash")
                        .HasDatabaseName("ix_archive_object_sha256hash");

                    b.HasIndex("TenantId", "ArchiveStatus")
                        .HasDatabaseName("ix_archive_object_tenant_id_archive_status");

                    b.HasIndex("TenantId", "ContentManifestId")
                        .HasDatabaseName("ix_archive_object_tenant_id_content_manifest_id");

                    b.HasIndex("TenantId", "ReceivedAt")
                        .HasDatabaseName("ix_archive_object_tenant_id_received_at");

                    b.HasIndex("ArchiveStatus", "NextIntegrityCheckAt", "IntegrityCheckLeaseUntil")
                        .HasDatabaseName("ix_archive_object_archive_status_next_integrity_check_at_integ");

                    b.HasIndex("ArchiveStatus", "RetentionUntil", "PurgeLeaseUntil")
                        .HasDatabaseName("ix_archive_object_archive_status_retention_until_purge_lease_u");

                    b.HasIndex("SourceSystem", "FileType", "Partner")
                        .HasDatabaseName("ix_archive_object_source_system_file_type_partner");

                    b.HasIndex("StorageProcessingStatus", "StorageProcessingNextAttemptAt", "StorageProcessingLeaseUntil")
                        .HasDatabaseName("ix_archive_object_storage_processing_status_storage_processing");

                    b.HasIndex("TenantId", "BucketName", "ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_archive_object_tenant_id_bucket_name_object_key");

                    b.HasIndex("TenantId", "BucketName", "StagingObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_archive_object_tenant_id_bucket_name_staging_object_key");

                    b.ToTable("archive_object", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_archive_object_deletion_requested", "archive_status <> 'DeletionRequested'\r\nOR (\r\n    deletion_requested_at IS NOT NULL\r\n    AND deletion_requested_by IS NOT NULL\r\n)");

                            t.HasCheckConstraint("ck_archive_object_purged", "archive_status <> 'Purged'\r\nOR purged_at IS NOT NULL");

                            t.HasCheckConstraint("ck_archive_object_size_bytes", "size_bytes >= 0");

                            t.HasCheckConstraint("ck_archive_object_storage_processing_attempt_count", "storage_processing_attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.BusinessReferenceType", b =>
                {
                    b.Property<int>("BusinessReferenceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("business_reference_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BusinessReferenceTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ReferenceTypeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_type_key");

                    b.HasKey("BusinessReferenceTypeId")
                        .HasName("pk_business_ref_type");

                    b.HasIndex("ReferenceTypeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_business_ref_type_reference_type_key");

                    b.ToTable("business_ref_type", "cirrus");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ContentChunk", b =>
                {
                    b.Property<long>("ContentChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("content_chunk_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContentChunkId"));

                    b.Property<string>("ChunkHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("chunk_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash_algorithm");

                    b.Property<long>("RawSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_size_bytes");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("ContentChunkId")
                        .HasName("pk_content_chunk");

                    b.HasIndex("TenantId", "HashAlgorithm", "ChunkHash")
                        .IsUnique()
                        .HasDatabaseName("ix_content_chunk_tenant_id_hash_algorithm_chunk_hash");

                    b.ToTable("content_chunk", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_content_chunk_raw_size", "raw_size_bytes > 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ContentManifest", b =>
                {
                    b.Property<long>("ContentManifestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("content_manifest_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContentManifestId"));

                    b.Property<int>("AverageChunkSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("average_chunk_size_bytes");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_count");

                    b.Property<string>("ChunkingAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("chunking_algorithm");

                    b.Property<int>("ChunkingAlgorithmVersion")
                        .HasColumnType("integer")
                        .HasColumnName("chunking_algorithm_version");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash_algorithm");

                    b.Property<int>("ManifestFormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("manifest_format_version");

                    b.Property<int>("MaximumChunkSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_chunk_size_bytes");

                    b.Property<int>("MinimumChunkSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_chunk_size_bytes");

                    b.Property<string>("OriginalHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("original_hash");

                    b.Property<long>("OriginalSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("original_size_bytes");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("ContentManifestId")
                        .HasName("pk_content_manifest");

                    b.HasAlternateKey("TenantId", "ContentManifestId")
                        .HasName("ak_content_manifests_tenant_id_content_manifest_id");

                    b.HasIndex("TenantId", "OriginalHash")
                        .HasDatabaseName("ix_content_manifest_tenant_id_original_hash");

                    b.ToTable("content_manifest", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_content_manifest_chunk_count", "chunk_count > 0");

                            t.HasCheckConstraint("ck_content_manifest_chunk_sizes", "minimum_chunk_size_bytes > 0 AND average_chunk_size_bytes >= minimum_chunk_size_bytes AND maximum_chunk_size_bytes >= average_chunk_size_bytes");

                            t.HasCheckConstraint("ck_content_manifest_original_size", "original_size_bytes >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.MachineIdentity", b =>
                {
                    b.Property<long>("MachineIdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("machine_identity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MachineIdentityId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MachineIdentityId")
                        .HasName("pk_machine_identity");

                    b.HasAlternateKey("TenantId", "MachineIdentityId")
                        .HasName("ak_machine_identity_tenant_id_machine_identity_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_machine_identity_tenant_id_name");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_machine_identity_tenant_id_status");

                    b.ToTable("machine_identity", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_machine_identity_disabled", "status <> 'Disabled' OR disabled_at IS NOT NULL");

                            t.HasCheckConstraint("ck_machine_identity_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.MachineIdentityPermission", b =>
                {
                    b.Property<long>("MachineIdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("machine_identity_id");

                    b.Property<string>("Permission")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission");

                    b.HasKey("MachineIdentityId", "Permission")
                        .HasName("pk_machine_identity_permission");

                    b.ToTable("machine_identity_permission", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_machine_identity_permission_value", "permission IN ('ArchiveRead', 'ArchiveWrite', 'ArchiveDelete', 'ArchiveVerify')");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ManifestChunk", b =>
                {
                    b.Property<long>("ContentManifestId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_manifest_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<long>("ContentChunkId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_chunk_id");

                    b.Property<long>("OriginalOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("original_offset");

                    b.Property<int>("RawLength")
                        .HasColumnType("integer")
                        .HasColumnName("raw_length");

                    b.HasKey("ContentManifestId", "SequenceNumber")
                        .HasName("pk_manifest_chunk");

                    b.HasIndex("ContentChunkId")
                        .HasDatabaseName("ix_manifest_chunk_content_chunk_id");

                    b.ToTable("manifest_chunk", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_manifest_chunk_length", "raw_length > 0");

                            t.HasCheckConstraint("ck_manifest_chunk_offset", "original_offset >= 0");

                            t.HasCheckConstraint("ck_manifest_chunk_sequence", "sequence_number >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.RetentionPolicy", b =>
                {
                    b.Property<int>("RetentionPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("retention_policy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RetentionPolicyId"));

                    b.Property<bool>("DeleteAfterExpiry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("delete_after_expiry");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("policy_name");

                    b.Property<int>("RetentionYears")
                        .HasColumnType("integer")
                        .HasColumnName("retention_years");

                    b.Property<bool>("WormRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("worm_required");

                    b.HasKey("RetentionPolicyId")
                        .HasName("pk_retention_policy");

                    b.HasIndex("PolicyName")
                        .IsUnique()
                        .HasDatabaseName("ix_retention_policy_policy_name");

                    b.ToTable("retention_policy", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_retention_policy_retention_years", "retention_years >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.SecurityAuditEvent", b =>
                {
                    b.Property<long>("SecurityAuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("security_audit_event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SecurityAuditEventId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("KeyId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key_id");

                    b.Property<long>("MachineIdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("machine_identity_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("SecurityAuditEventId")
                        .HasName("pk_security_audit_event");

                    b.HasIndex("MachineIdentityId", "EventTimestamp")
                        .HasDatabaseName("ix_security_audit_event_machine_identity_id_event_timestamp");

                    b.HasIndex("TenantId", "EventTimestamp")
                        .HasDatabaseName("ix_security_audit_event_tenant_id_event_timestamp");

                    b.HasIndex("TenantId", "MachineIdentityId")
                        .HasDatabaseName("ix_security_audit_event_tenant_id_machine_identity_id");

                    b.ToTable("security_audit_event", "cirrus");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.StorageLocation", b =>
                {
                    b.Property<long>("StorageLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("storage_location_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StorageLocationId"));

                    b.Property<string>("CompressionAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("compression_algorithm");

                    b.Property<int>("CompressionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("compression_version");

                    b.Property<long>("ContentChunkId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_chunk_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("PackOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("pack_offset");

                    b.Property<int>("RawLength")
                        .HasColumnType("integer")
                        .HasColumnName("raw_length");

                    b.Property<int>("StorageFormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("storage_format_version");

                    b.Property<long>("StoragePackId")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_pack_id");

                    b.Property<int>("StoredLength")
                        .HasColumnType("integer")
                        .HasColumnName("stored_length");

                    b.HasKey("StorageLocationId")
                        .HasName("pk_storage_location");

                    b.HasIndex("ContentChunkId")
                        .HasDatabaseName("ix_storage_location_content_chunk_id");

                    b.HasIndex("StoragePackId", "PackOffset")
                        .IsUnique()
                        .HasDatabaseName("ix_storage_location_storage_pack_id_pack_offset");

                    b.ToTable("storage_location", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_storage_location_lengths", "stored_length > 0 AND raw_length > 0");

                            t.HasCheckConstraint("ck_storage_location_offset", "pack_offset >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.StoragePack", b =>
                {
                    b.Property<long>("StoragePackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("storage_pack_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StoragePackId"));

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bucket_name");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash_algorithm");

                    b.Property<int>("MaintenanceAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_attempts");

                    b.Property<string>("MaintenanceError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("maintenance_error");

                    b.Property<string>("MaintenanceLeaseOwner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("maintenance_lease_owner");

                    b.Property<DateTimeOffset?>("MaintenanceLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("maintenance_lease_until");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<int>("PackFormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("pack_format_version");

                    b.Property<string>("PackHash")
                        .HasColumnType("char(64)")
                        .HasColumnName("pack_hash");

                    b.Property<string>("PackStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pack_status");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageVersionId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_version_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("StoragePackId")
                        .HasName("pk_storage_pack");

                    b.HasIndex("MaintenanceLeaseUntil")
                        .HasDatabaseName("ix_storage_pack_maintenance_lease_until");

                    b.HasIndex("PackStatus", "CreatedAt")
                        .HasDatabaseName("ix_storage_pack_pack_status_created_at");

                    b.HasIndex("TenantId", "BucketName", "ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_storage_pack_tenant_id_bucket_name_object_key");

                    b.ToTable("storage_pack", "cirrus", t =>
                        {
                            t.HasCheckConstraint("ck_storage_pack_size", "size_bytes >= 0");
                        });
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.Tenant", b =>
                {
                    b.Property<long>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TenantId"));

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bucket_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultRetentionPolicyId")
                        .HasColumnType("integer")
                        .HasColumnName("default_retention_policy_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EncryptionKeyId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("encryption_key_id");

                    b.Property<string>("ObjectKeyPrefix")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key_prefix");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant");

                    b.HasIndex("DefaultRetentionPolicyId")
                        .HasDatabaseName("ix_tenant_default_retention_policy_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tenant_status");

                    b.HasIndex("BucketName", "ObjectKeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_bucket_name_object_key_prefix");

                    b.ToTable("tenant", "cirrus");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ApiKeyCredential", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.MachineIdentity", "MachineIdentity")
                        .WithMany("ApiKeyCredentials")
                        .HasForeignKey("MachineIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_credential_machine_identities_machine_identity_id");

                    b.HasOne("MTSM.Cirrus.Core.Entities.ApiKeyCredential", "ReplacedBy")
                        .WithMany()
                        .HasForeignKey("ReplacedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_api_key_credential_api_key_credential_replaced_by_id");

                    b.Navigation("MachineIdentity");

                    b.Navigation("ReplacedBy");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveBusinessReference", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.BusinessReferenceType", "BusinessReferenceType")
                        .WithMany("BusinessReferences")
                        .HasForeignKey("BusinessReferenceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_archive_business_ref_business_reference_types_business_refe");

                    b.HasOne("MTSM.Cirrus.Core.Entities.ArchiveObject", "ArchiveObject")
                        .WithMany("BusinessReferences")
                        .HasForeignKey("TenantId", "ArchiveObjectId")
                        .HasPrincipalKey("TenantId", "ArchiveObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_archive_business_ref_archive_objects_tenant_id_archive_obje");

                    b.Navigation("ArchiveObject");

                    b.Navigation("BusinessReferenceType");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveErrorQueueItem", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.ArchiveObject", "ArchiveObject")
                        .WithMany("Errors")
                        .HasForeignKey("ArchiveObjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_archive_error_queue_archive_objects_archive_object_id");

                    b.Navigation("ArchiveObject");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveEvent", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.ArchiveObject", "ArchiveObject")
                        .WithMany("Events")
                        .HasForeignKey("TenantId", "ArchiveObjectId")
                        .HasPrincipalKey("TenantId", "ArchiveObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_archive_event_archive_objects_tenant_id_archive_object_id");

                    b.Navigation("ArchiveObject");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveObject", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.RetentionPolicy", "RetentionPolicy")
                        .WithMany("ArchiveObjects")
                        .HasForeignKey("RetentionPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_archive_object_retention_policies_retention_policy_id");

                    b.HasOne("MTSM.Cirrus.Core.Entities.Tenant", "Tenant")
                        .WithMany("ArchiveObjects")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_archive_object_tenants_tenant_id");

                    b.HasOne("MTSM.Cirrus.Core.Entities.ContentManifest", "ContentManifest")
                        .WithMany("ArchiveObjects")
                        .HasForeignKey("TenantId", "ContentManifestId")
                        .HasPrincipalKey("TenantId", "ContentManifestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_archive_object_content_manifests_tenant_id_content_manifest");

                    b.Navigation("ContentManifest");

                    b.Navigation("RetentionPolicy");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ContentChunk", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.Tenant", "Tenant")
                        .WithMany("ContentChunks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_chunk_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ContentManifest", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.Tenant", "Tenant")
                        .WithMany("ContentManifests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_manifest_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.MachineIdentity", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_machine_identity_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.MachineIdentityPermission", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.MachineIdentity", "MachineIdentity")
                        .WithMany("Permissions")
                        .HasForeignKey("MachineIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_machine_identity_permission_machine_identity_machine_identi");

                    b.Navigation("MachineIdentity");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ManifestChunk", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.ContentChunk", "ContentChunk")
                        .WithMany("ManifestChunks")
                        .HasForeignKey("ContentChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_manifest_chunk_content_chunk_content_chunk_id");

                    b.HasOne("MTSM.Cirrus.Core.Entities.ContentManifest", "ContentManifest")
                        .WithMany("Chunks")
                        .HasForeignKey("ContentManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_manifest_chunk_content_manifest_content_manifest_id");

                    b.Navigation("ContentChunk");

                    b.Navigation("ContentManifest");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.SecurityAuditEvent", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_security_audit_event_tenants_tenant_id");

                    b.HasOne("MTSM.Cirrus.Core.Entities.MachineIdentity", "MachineIdentity")
                        .WithMany()
                        .HasForeignKey("TenantId", "MachineIdentityId")
                        .HasPrincipalKey("TenantId", "MachineIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_security_audit_event_machine_identity_tenant_id_machine_ide");

                    b.Navigation("MachineIdentity");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.StorageLocation", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.ContentChunk", "ContentChunk")
                        .WithMany("StorageLocations")
                        .HasForeignKey("ContentChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_storage_location_content_chunk_content_chunk_id");

                    b.HasOne("MTSM.Cirrus.Core.Entities.StoragePack", "StoragePack")
                        .WithMany("StorageLocations")
                        .HasForeignKey("StoragePackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_storage_location_storage_packs_storage_pack_id");

                    b.Navigation("ContentChunk");

                    b.Navigation("StoragePack");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.StoragePack", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.Tenant", "Tenant")
                        .WithMany("StoragePacks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_storage_pack_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.Tenant", b =>
                {
                    b.HasOne("MTSM.Cirrus.Core.Entities.RetentionPolicy", "DefaultRetentionPolicy")
                        .WithMany()
                        .HasForeignKey("DefaultRetentionPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tenant_retention_policy_default_retention_policy_id");

                    b.Navigation("DefaultRetentionPolicy");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ArchiveObject", b =>
                {
                    b.Navigation("BusinessReferences");

                    b.Navigation("Errors");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.BusinessReferenceType", b =>
                {
                    b.Navigation("BusinessReferences");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ContentChunk", b =>
                {
                    b.Navigation("ManifestChunks");

                    b.Navigation("StorageLocations");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.ContentManifest", b =>
                {
                    b.Navigation("ArchiveObjects");

                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.MachineIdentity", b =>
                {
                    b.Navigation("ApiKeyCredentials");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.RetentionPolicy", b =>
                {
                    b.Navigation("ArchiveObjects");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.StoragePack", b =>
                {
                    b.Navigation("StorageLocations");
                });

            modelBuilder.Entity("MTSM.Cirrus.Core.Entities.Tenant", b =>
                {
                    b.Navigation("ArchiveObjects");

                    b.Navigation("ContentChunks");

                    b.Navigation("ContentManifests");

                    b.Navigation("StoragePacks");
                });
#pragma warning restore 612, 618
        }
    }
}
